// <auto-generated />
using System;
using EclipseWorks.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EclipseWorks.Infrastructure.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20250121164522_table_task_update")]
    partial class table_task_update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EclipseWorks.Core.Models.OperationLogModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("date");

                    b.Property<string>("ModifiedData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modifieddata");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("table");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("operationlog");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.ProjectModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("project");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.TaskCommentModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("comment");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("taskid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("taskcomment");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.TaskModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("description");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("projectid");

                    b.Property<short>("TaskPriorityId")
                        .HasColumnType("smallint")
                        .HasColumnName("taskpriorityid");

                    b.Property<short>("TaskStatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("taskstatusid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("task");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean")
                        .HasColumnName("ismanager");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("registrationdate");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = true,
                            Email = "ivan@mail.com",
                            Hash = "Bgww0uoznBPlYtfo8tm/YNQohyinF/ib47IdN76tANk=",
                            IsManager = true,
                            Name = "Ivan Liebana",
                            Password = "5ex3AdaQD2k1pnObA3NOm3kPnaFoS4bdhKMIJiClr0c=",
                            RegistrationDate = new DateTime(2025, 1, 21, 13, 45, 21, 594, DateTimeKind.Local).AddTicks(5276)
                        },
                        new
                        {
                            Id = 2L,
                            Active = true,
                            Email = "aline@mail.com",
                            Hash = "LJCEaNu2aw/et7eFmKzEp3XArNVCQD+Nzl84SgVxd1g=",
                            IsManager = false,
                            Name = "Aline Paula",
                            Password = "8s45fbEH6eLpmn0svRejrgvf+K/m/LMVRot6uRTzygw=",
                            RegistrationDate = new DateTime(2025, 1, 21, 13, 45, 21, 594, DateTimeKind.Local).AddTicks(5373)
                        },
                        new
                        {
                            Id = 3L,
                            Active = true,
                            Email = "marialaura@mail.com",
                            Hash = "LYoFpSK5uQj/CcHTTmNNdo+bdlFYmKF3iVZ5n9g1HE4=",
                            IsManager = false,
                            Name = "Maria Laura",
                            Password = "ywDgRo6LP3g/qmx8RACcTFNBVWknwfRDgc7KxWWu5XM=",
                            RegistrationDate = new DateTime(2025, 1, 21, 13, 45, 21, 594, DateTimeKind.Local).AddTicks(5420)
                        },
                        new
                        {
                            Id = 4L,
                            Active = true,
                            Email = "henry@mail.com",
                            Hash = "cOK+6SZCckh5OKGvEAXG1WX+qWT2sIIp+yIxpWEwiKY=",
                            IsManager = false,
                            Name = "Henry",
                            Password = "exsHteB5ajFQTv0nSrf6GE1akWr1AA99fcCAUWX3CnY=",
                            RegistrationDate = new DateTime(2025, 1, 21, 13, 45, 21, 594, DateTimeKind.Local).AddTicks(5464)
                        });
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.OperationLogModel", b =>
                {
                    b.HasOne("EclipseWorks.Core.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.ProjectModel", b =>
                {
                    b.HasOne("EclipseWorks.Core.Models.UserModel", "User")
                        .WithMany("Project")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.TaskCommentModel", b =>
                {
                    b.HasOne("EclipseWorks.Core.Models.TaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.TaskModel", b =>
                {
                    b.HasOne("EclipseWorks.Core.Models.ProjectModel", "Project")
                        .WithMany("Task")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.ProjectModel", b =>
                {
                    b.Navigation("Task");
                });

            modelBuilder.Entity("EclipseWorks.Core.Models.UserModel", b =>
                {
                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
